server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      locator:
        enabled: true
      routes:
        -  id: provider
           uri: lb://provider
           predicates:
             -  Path=/Test/**
           filters:
             -  SwaggerHeaderFilter
             -  StripPrefix=1
      x-forwarded:
        enabled: false